# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b8613f6ee4117dd088a537701d4de12f160eb6992b72508a27a4ad36d6a584172b0a38892d2b4a8f5af8157e5dcf8c7b78bf865588985987cf8702e2d7070ad

test:
  secret_key_base: 844137eee6cdc13375870bebde88430a8d62eec13fb34908c5698e4fae60c81f82bfeb70f651737f9503a90a4eb3b5465b8effd966613f6e0a696336ae67b67a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
